name: 'Report Jest Audit'
description: 'report jest/vitest test stats for one or more coding challenges'
inputs:
  track:
    description: 'if this is a backend, frontend or cloud progamming challenge'
    required: true
  about:
    description: 'file containing extra details about the project'
    required: true
  server:  
    description: 'base API URL'
    required: true
  sheetid:  
    description: 'the ID of the Google spreadsheet'
    required: true
  token:  
    description: 'Auth token for the API call'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'